/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author user name
 */
public class UIKafeMenu extends javax.swing.JFrame {

    /**
     * Creates new form UIKafeMenu
     */
    public UIKafeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Mi1 = new javax.swing.JTextField();
        Mi2 = new javax.swing.JTextField();
        Mi3 = new javax.swing.JTextField();
        Mi4 = new javax.swing.JTextField();
        Mi5 = new javax.swing.JTextField();
        Mi6 = new javax.swing.JTextField();
        Mi7 = new javax.swing.JTextField();
        Mi8 = new javax.swing.JTextField();
        Mi9 = new javax.swing.JTextField();
        Mi10 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Ma1 = new javax.swing.JTextField();
        Ma3 = new javax.swing.JTextField();
        Ma2 = new javax.swing.JTextField();
        Ma4 = new javax.swing.JTextField();
        Ma5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        HTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));

        jLabel1.setFont(new java.awt.Font("MV Boli", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seketnip Kafe Menu");

        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lanjut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Minuman");

        jLabel9.setText("Red Velvet    Rp. 17.000");

        jLabel4.setText("Milktea          Rp. 10.000");

        jLabel5.setText("Milkshake      Rp. 12.000");

        jLabel6.setText("Coffe Latte   Rp. 10.000");

        jLabel7.setText("Matcha         Rp. 15.000");

        jLabel8.setText("Thai Tea       Rp. 12.000");

        jLabel10.setText("Cappucino    Rp. 12.000");

        jLabel11.setText("Expresso      Rp. 10.000");

        jLabel12.setText("Caramel        Rp. 15.000");

        jLabel13.setText("Americano    Rp. 10.000");

        jLabel14.setText("Qty");

        Mi1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi1.setText("0");
        Mi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi1ActionPerformed(evt);
            }
        });
        Mi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi1KeyTyped(evt);
            }
        });

        Mi2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi2.setText("0");
        Mi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi2ActionPerformed(evt);
            }
        });
        Mi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi2KeyTyped(evt);
            }
        });

        Mi3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi3.setText("0");
        Mi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi3ActionPerformed(evt);
            }
        });
        Mi3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi3KeyTyped(evt);
            }
        });

        Mi4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi4.setText("0");
        Mi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi4ActionPerformed(evt);
            }
        });
        Mi4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi4KeyTyped(evt);
            }
        });

        Mi5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi5.setText("0");
        Mi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi5ActionPerformed(evt);
            }
        });
        Mi5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi5KeyTyped(evt);
            }
        });

        Mi6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi6.setText("0");
        Mi6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi6ActionPerformed(evt);
            }
        });
        Mi6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi6KeyTyped(evt);
            }
        });

        Mi7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi7.setText("0");
        Mi7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi7ActionPerformed(evt);
            }
        });
        Mi7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi7KeyTyped(evt);
            }
        });

        Mi8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi8.setText("0");
        Mi8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi8ActionPerformed(evt);
            }
        });
        Mi8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi8KeyTyped(evt);
            }
        });

        Mi9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi9.setText("0");
        Mi9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi9ActionPerformed(evt);
            }
        });
        Mi9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi9KeyTyped(evt);
            }
        });

        Mi10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Mi10.setText("0");
        Mi10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi10ActionPerformed(evt);
            }
        });
        Mi10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mi10KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(Mi3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mi10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mi10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                            .addComponent(Mi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel14)
                                                                                                        .addGap(18, 18, 18))
                                                                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGap(26, 26, 26)))
                                                                                                .addComponent(jLabel4)))
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel5))
                                                                                    .addComponent(Mi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addComponent(Mi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel7))
                                                                    .addComponent(Mi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel8))
                                                            .addComponent(Mi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel9))
                                                    .addComponent(Mi6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10))
                                            .addComponent(Mi7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(Mi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addComponent(Mi9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Makanan");

        jLabel15.setText("Rainbowcake      Rp. 15.000");

        jLabel16.setText("Roti Bakar           Rp. 12.000");

        jLabel17.setText("Kentang Goreng Rp. 10.000");

        jLabel18.setText("Sosis Bakar         Rp. 15.000");

        jLabel19.setText("Sandwich            Rp. 12.000");

        Ma1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Ma1.setText("0");
        Ma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ma1ActionPerformed(evt);
            }
        });
        Ma1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ma1KeyTyped(evt);
            }
        });

        Ma3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Ma3.setText("0");
        Ma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ma3ActionPerformed(evt);
            }
        });
        Ma3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ma3KeyTyped(evt);
            }
        });

        Ma2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Ma2.setText("0");
        Ma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ma2ActionPerformed(evt);
            }
        });
        Ma2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ma2KeyTyped(evt);
            }
        });

        Ma4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Ma4.setText("0");
        Ma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ma4ActionPerformed(evt);
            }
        });
        Ma4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ma4KeyTyped(evt);
            }
        });

        Ma5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Ma5.setText("0");
        Ma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ma5ActionPerformed(evt);
            }
        });
        Ma5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ma5KeyTyped(evt);
            }
        });

        jLabel20.setText("Qty");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ma2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ma4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ma5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(Ma3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(Ma1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ma5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(Ma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16))
                                            .addComponent(Ma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))
                                    .addComponent(Ma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))
                            .addComponent(Ma4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        HTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HTotal.setText("Total yang harus dibayar adalah ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HTotal)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(12, 12, 12)
                        .addComponent(HTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi1ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Mi1ActionPerformed

    private void Mi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi5ActionPerformed

    private void Mi6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi6ActionPerformed

    private void Mi10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi10ActionPerformed

    private void Mi7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi7ActionPerformed

    private void Mi8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi8ActionPerformed

    private void Mi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi2ActionPerformed

    private void Mi9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi9ActionPerformed

    private void Mi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi3ActionPerformed

    private void Mi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mi4ActionPerformed

    private void Ma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ma1ActionPerformed

    private void Ma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ma3ActionPerformed

    private void Ma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ma2ActionPerformed

    private void Ma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ma4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ma4ActionPerformed

    private void Ma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ma5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ma5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pilihan[]={"Ya", "Tidak"};
        int jawab = JOptionPane.showOptionDialog(null, "Apakah anda yakin dengan pesanan anda?", "pemberitahuan", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[0]);

if (jawab == JOptionPane.NO_OPTION){
JOptionPane.showMessageDialog(null, "Silakan ubah kembali pesanan anda");
}
else if(jawab == JOptionPane.YES_OPTION){
    JOptionPane.showMessageDialog(null, "Silakan Siapkan uang pembayaran"  + "\n" +  "dan berikan daftar pesanan ke kasir");
new UIFinal().setVisible(true);
this.setVisible(false);}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int NMi1 = Integer.parseInt(Mi1.getText()) * 10000;
int NMi2 = Integer.parseInt(Mi2.getText()) * 12000;
int NMi3 = Integer.parseInt(Mi3.getText()) * 10000;
int NMi4 = Integer.parseInt(Mi4.getText()) * 15000;
int NMi5 = Integer.parseInt(Mi5.getText()) * 12000;
int NMi6 = Integer.parseInt(Mi6.getText()) * 17000;
int NMi7 = Integer.parseInt(Mi7.getText()) * 12000;
int NMi8 = Integer.parseInt(Mi8.getText()) * 10000;
int NMi9 = Integer.parseInt(Mi9.getText()) * 15000;
int NMi10 = Integer.parseInt(Mi10.getText()) * 10000;
int NMa1 = Integer.parseInt(Ma1.getText()) * 15000;
int NMa2 = Integer.parseInt(Ma2.getText()) * 12000;
int NMa3 = Integer.parseInt(Ma3.getText()) * 10000;
int NMa4 = Integer.parseInt(Ma4.getText()) * 15000;
int NMa5 = Integer.parseInt(Ma5.getText()) * 12000;
int total = NMi1 + NMi2 + NMi3 + NMi4 + NMi5 + NMi6 + NMi7 + NMi8 + NMi9 + NMi10 + NMa1 + NMa2 + NMa3 + NMa4 + NMa5;
//tampilkan hasil ke tekxt field
HTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Mi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi1KeyTyped
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_Mi1KeyTyped

    private void Mi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi2KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi2KeyTyped

    private void Mi3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi3KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi3KeyTyped

    private void Mi4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi4KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi4KeyTyped

    private void Mi5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi5KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi5KeyTyped

    private void Mi6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi6KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi6KeyTyped

    private void Mi7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi7KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi7KeyTyped

    private void Mi8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi8KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi8KeyTyped

    private void Mi9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi9KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi9KeyTyped

    private void Mi10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mi10KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Mi10KeyTyped

    private void Ma1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ma1KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Ma1KeyTyped

    private void Ma2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ma2KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Ma2KeyTyped

    private void Ma3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ma3KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Ma3KeyTyped

    private void Ma4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ma4KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Ma4KeyTyped

    private void Ma5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ma5KeyTyped
        // TODO add your handling code here:
char c= evt.getKeyChar();
if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
    evt.consume();
}
    }//GEN-LAST:event_Ma5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIKafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIKafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIKafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIKafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIKafeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HTotal;
    private javax.swing.JTextField Ma1;
    private javax.swing.JTextField Ma2;
    private javax.swing.JTextField Ma3;
    private javax.swing.JTextField Ma4;
    private javax.swing.JTextField Ma5;
    private javax.swing.JTextField Mi1;
    private javax.swing.JTextField Mi10;
    private javax.swing.JTextField Mi2;
    private javax.swing.JTextField Mi3;
    private javax.swing.JTextField Mi4;
    private javax.swing.JTextField Mi5;
    private javax.swing.JTextField Mi6;
    private javax.swing.JTextField Mi7;
    private javax.swing.JTextField Mi8;
    private javax.swing.JTextField Mi9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
